#!/bin/bash

DIR="$(dirname "$(readlink -f "$0")")"
SOURCE=$(head -n 1 <$DIR/folders)
DEST=$(tail -n 1 <$DIR/folders)
while true; do
    read -p "What do you want to do? [m/u/k] or 'c' to cancel >" INIT
    case $INIT in
        [Mm]* ) $(sshfs -o reconnect $SOURCE $DEST); break;; #mount the remote directory according to folders specified in ./folders
        [Uu]* ) $(umount -l $DEST && fusermount -u $DEST); break;; #clean unmount
        [Kk]* ) PROC=($(ps -ef | grep "sshfs -o reconnect")); #kill the process if it hangs
                kill -9 ${PROC[1]};
                (umount -l $DEST && fusermount -u $DEST); break;;
        [Cc]* ) exit;;
        * ) echo "Please answer one of the four options.";;
    esac
done
